@startuml

Class Juego

Class Tron

Class Personaje

Class Jugador{
    + Controlar () 
}

Class Enemigo{
    + Bloquear ()
    + Acelerar ()
}

Class Moto{
    + Moverse ()
}

Class Controlador{
    + Direccionar ()
}

Class Boton{
    + Acelerar ()
}

Class Dibujo{
    + Imprimir ()
}

CLass Escenario{
    + Limitar () 
}

Class Humano{
    + Interaccion ()
}

Class Nivel{
    + Iniciar ()
    + Finalizar ()
}

Class Victorias{

    + Agregar ()
}

Class Estela{
    + Obstaculizar ()
}

Humano --|> Personaje
Moto --|> Personaje
Jugador o-- Moto
Jugador o-- Enemigo
Enemigo --|> Personaje
Enemigo o-- Moto
Moto *-- Estela
Moto o-- Turbo
Nivel *-- Victorias
Nivel *-- Enemigo
Juego *-- Nivel
Juego *-- Personaje
Juego *-- Escenario
Juego o-- Dibujo
Jugador o-- Controlador


Juego "1" *-- "2"Jugador
Jugador "2" *-- "1"Moto
Moto "1" *-- "1" Estela
Moto "1" *-- "1" Turbo
Nivel "1" *-- "1" Enemigo
Enemigo "1" *-- "1" Moto
Nivel "1" *-- "1" Enemigo
Nivel "1" *-- "3" Victorias



@enduml